// Generated by CoffeeScript 1.9.3
var $timezone_used;

$timezone_used = 'Europe/Warsaw';

QUnit.module("Ankieta");

QUnit.test("ankieta - wywiad/3. sekcja", function($assert) {
  var $arrivalDate, $record, $validator;
  $record = {
    strokeInThePast: 'YES',
    pastStrokeYear: new Date().getFullYear(),
    pastStrokeMonth: 1
  };
  $arrivalDate = moment({
    month: 0,
    day: 1
  }).valueOf();
  $validator = new StrictValidation($record);
  $assert.ok($validator.thirdSection($arrivalDate), "Ten sam dzień");
  $record.pastStrokeYear = new Date().getFullYear() - 1;
  $validator.setInterview($record);
  $assert.ok($validator.thirdSection($arrivalDate), "Zawał rok przed przyjęciem");
  $record.pastStrokeYear = new Date().getFullYear();
  $arrivalDate = moment({
    month: 1,
    day: 1
  }).valueOf();
  $validator.setInterview($record);
  $assert.ok($validator.thirdSection($arrivalDate), "Zawał miesiąc przed przyjęciem");
  $record.pastStrokeMonth = 3;
  $validator.setInterview($record);
  $assert.notOk($validator.thirdSection($arrivalDate), "Zawał miesiąc po przyjęciu");
  $arrivalDate = moment({
    year: $record.pastStrokeYear - 1,
    month: 1,
    day: 1
  }).valueOf();
  $validator.setInterview($record);
  $assert.notOk($validator.thirdSection($arrivalDate), "Zawał rok po przyjęciu");
  $record.strokeInThePast = 'NO';
  $validator.setInterview($record);
  $assert.ok($validator.thirdSection($arrivalDate), "Nie było wcześniejszego zawału");
  delete $record.strokeInThePast;
  $validator.setInterview($record);
  $assert.notOk($validator.thirdSection($arrivalDate), "Brak informacji o zawale");
  $record = {
    strokeInThePast: 'NO',
    diabetes: 'NO'
  };
  $validator.setInterview($record);
  $assert.ok($validator.thirdSection($arrivalDate), "Brak cukrzycy");
  $record.diabetes = 'YES';
  $validator.setInterview($record);
  $assert.notOk($validator.thirdSection($arrivalDate), "Brak pomiarów glukozy");
  $record.glucoseLevelDay5to7 = 12;
  $validator.setInterview($record);
  $assert.notOk($validator.thirdSection($arrivalDate), "Brak 1. pomiaru glukozy");
  $record.glucoseLevelDay1 = 12;
  $validator.setInterview($record);
  $assert.ok($validator.thirdSection($arrivalDate), "Cukrzyca - wszystko jest");
  delete $record.glucoseLevelDay5to7;
  $validator.setInterview($record);
  $assert.notOk($validator.thirdSection($arrivalDate), "Brak 2. pomiaru glukozy");
  $record = {
    strokeInThePast: 'NO',
    ischemicHeartDisease: 'NO'
  };
  $validator.setInterview($record);
  $assert.ok($validator.thirdSection($arrivalDate), "CCS - nie");
  $record.ischemicHeartDisease = 'YES';
  $validator.setInterview($record);
  $assert.notOk($validator.thirdSection($arrivalDate), "CCS - brak klasy");
  $record.ccsClass = 'I';
  $validator.setInterview($record);
  return $assert.ok($validator.thirdSection($arrivalDate), "CCS - wszystko jest");
});

QUnit.test("ankieta - leczenie szpitalne/5. sekcja", function($assert) {
  var $record, $validator;
  $record = {
    drugsOnHospitalisation: null,
    otherDrugsOnHospitalisation: null
  };
  $validator = new StrictValidation($record);
  $assert.notOk($validator.fifthSection(), 'Brak leków');
  $record.drugsOnHospitalisation = [];
  $validator.setInterview($record);
  $assert.notOk($validator.fifthSection(), 'Brak leków - tablica');
  $record.drugsOnHospitalisation = ['ARB', 'B_BLOCKER', 'CALCIUM_CHANNELS_BLOCKER'];
  $validator.setInterview($record);
  $assert.ok($validator.fifthSection(), 'Zwykłe leki');
  $record.drugsOnHospitalisation = ['OTHER'];
  $validator.setInterview($record);
  $assert.notOk($validator.fifthSection(), 'Inne leki - nieokreślone');
  $record.otherDrugsOnHospitalisation = 'ibuprom';
  $validator.setInterview($record);
  return $assert.ok($validator.fifthSection(), 'Inne leki - określone');
});

//# sourceMappingURL=tests.js.map
