// Generated by CoffeeScript 1.9.3
importScripts('../vendor/lazy.min.js');

importScripts('../vendor/fetch.js');

importScripts('common.js');

self.addEventListener('message', function(e) {
  var data, res;
  data = e.data;
  switch (data.cmd) {
    case 'start':
      res = fetch('../../../' + route_uri('#new-measurements') + '?just_data=1', {
        headers: {
          'Authorization': 'Basic ' + data.auth
        }
      });
      return res.then(check_status).then(function(resp) {
        return resp.json();
      }).then(function(json) {
        var measurements;
        measurements = fix_measurements(Lazy(json.data)).filter(function(val) {
          return val.patient == null;
        }).size();
        self.postMessage(measurements);
        return self.close();
      })["catch"](function(e) {
        console.log('measurements updater error');
        return self.close();
      });
  }
}, false);

//# sourceMappingURL=measurements.js.map
