// Generated by CoffeeScript 1.10.0
var $auth_data, $curr_ajax_request, $curr_tab, $datepicker_settings, $feedbackIcons, $horizontal_form_row, $last_activity, $new_measurements_opened, $other_user_logout, $prev_tab, $since, $timezone_used, $username;

$curr_tab = $prev_tab = null;

$feedbackIcons = {
  valid: 'void',
  invalid: 'fa fa-exclamation-circle fa-lg icon-fix',
  validating: 'fa fa-refresh fa-lg icon-fix'
};

$curr_ajax_request = null;

$horizontal_form_row = '<div class="fluid-row"> <div class="col-xs-12"> <div class="form-group"> <label class="col-sm-2 control-label dependent-label"></label> <div class="col-xs-5"> {label_content} </div> </div> </div> </div>';

$since = {
  '#new-measurements': 0,
  '#all-measurements': 0,
  '#all-examinations': 0,
  '#to-fill': 0,
  '#phones': 0
};

$auth_data = '';

$last_activity = 0;

$other_user_logout = false;

$username = null;

$new_measurements_opened = false;

$datepicker_settings = {
  language: 'pl',
  pickTime: false,
  maxDate: new Date()
};

$timezone_used = 'Europe/Warsaw';

//# sourceMappingURL=config.js.map
